### ISSUE TITLE
The performance of VisDrone

### ISSUE THREAD

**Issue by caiyaya** [PuAnysh/UFPMP-Det#4]
学长您好，我对您的工作非常感兴趣，但是在UFP部分我遇到了一些问题，想请教您一下。
我在使用您提供的数据集和ckp后，
1）对于coarse_det阶段，得到的结果如下：
![image](https://user-images.githubusercontent.com/89434519/171997256-87505ce8-294e-4b87-aeff-d2b7e6c6efd9.png)
2）对于MP_Det阶段，得到的结果如下：
<img width="602" alt="image" src="https://user-images.githubusercontent.com/89434519/171997285-f42be6e3-1129-421f-a670-c99aa61a979d.png">
1）是coarse_det在原始数据集上测试的结果，2)是按照您给的测试方式，使用ufpmp_det_eval.py 得到的结果。
想问下学长，正确的测试方式，以及如何获得更好的模型结果？

**Comment by Janspiry** [comment]
@caiyaya , hello, 我使用了提供的ckpt与json文件，是可以获得和论文接近的结果的。第二个阶段测试有些问题吧？
![image](https://user-images.githubusercontent.com/32922494/173358286-2470df16-cf23-48f4-9926-14b0f17a0748.png)

**Comment by caiyaya** [comment]
> @caiyaya , hello, 我使用了提供的ckpt与json文件，是可以获得和论文接近的结果的。第二个阶段测试有些问题吧？ ![image](https://user-images.githubusercontent.com/32922494/173358286-2470df16-cf23-48f4-9926-14b0f17a0748.png)

感谢您的回复！我是使用了ckpt，以及提供的测试文件(ufpmp_det_eval.py)，我的理解是使用coarse det完成初步预测并生成行的Mosic image，然后使用Mp-det进行预测，并生成新的json文件，最后和val数据集提供的json文件(instances_UAVval.json)进行验证。我这边的测试结果似乎没有达到论文所给定的精度，我不知道是不是没有理解论文的意思或是哪里出现了问题？
By the way,  您这里第二行MP-Det是在生成的UFP数据集上进行验证的结果吗？第三行应该是在原始数据集上的测试结果？

**Comment by caiyaya** [comment]
> > @caiyaya , hello, 我使用了提供的ckpt与json文件，是可以获得和论文接近的结果的。第二个阶段测试有些问题吧？ ![image](https://user-images.githubusercontent.com/32922494/173358286-2470df16-cf23-48f4-9926-14b0f17a0748.png)
> 
> 感谢您的回复！我是使用了ckpt，以及提供的测试文件(ufpmp_det_eval.py)，我的理解是使用coarse det完成初步预测并生成行的Mosic image，然后使用Mp-det进行预测，并生成新的json文件，最后和val数据集提供的json文件(instances_UAVval.json)进行验证。我这边的测试结果似乎没有达到论文所给定的精度，我不知道是不是没有理解论文的意思或是哪里出现了问题？ By the way, 您这里第二行MP-Det是在生成的UFP数据集上进行验证的结果吗？第三行应该是在原始数据集上的测试结果？

我这里重新更换了mmdetection版本，并重新检查了所有的参数，获得了新的结果。（还是和论文的结果有些差距，mAP低0.7，mAP50 低5）
![image](https://user-images.githubusercontent.com/89434519/173364289-c38dea67-9469-443f-ad92-7cd3b85eafd3.png)

**Comment by Janspiry** [comment]
> > @caiyaya , hello, 我使用了提供的ckpt与json文件，是可以获得和论文接近的结果的。第二个阶段测试有些问题吧？ ![image](https://user-images.githubusercontent.com/32922494/173358286-2470df16-cf23-48f4-9926-14b0f17a0748.png)
> 
> 感谢您的回复！我是使用了ckpt，以及提供的测试文件(ufpmp_det_eval.py)，我的理解是使用coarse det完成初步预测并生成行的Mosic image，然后使用Mp-det进行预测，并生成新的json文件，最后和val数据集提供的json文件(instances_UAVval.json)进行验证。我这边的测试结果似乎没有达到论文所给定的精度，我不知道是不是没有理解论文的意思或是哪里出现了问题？ By the way, 您这里第二行MP-Det是在生成的UFP数据集上进行验证的结果吗？第三行应该是在原始数据集上的测试结果？

是的，第二行只是单独测试MP-Net。第三行也就是完整你说的流程。

**Comment by Janspiry** [comment]
> > > @caiyaya , hello, 我使用了提供的ckpt与json文件，是可以获得和论文接近的结果的。第二个阶段测试有些问题吧？ ![image](https://user-images.githubusercontent.com/32922494/173358286-2470df16-cf23-48f4-9926-14b0f17a0748.png)
> > 
> > 
> > 感谢您的回复！我是使用了ckpt，以及提供的测试文件(ufpmp_det_eval.py)，我的理解是使用coarse det完成初步预测并生成行的Mosic image，然后使用Mp-det进行预测，并生成新的json文件，最后和val数据集提供的json文件(instances_UAVval.json)进行验证。我这边的测试结果似乎没有达到论文所给定的精度，我不知道是不是没有理解论文的意思或是哪里出现了问题？ By the way, 您这里第二行MP-Det是在生成的UFP数据集上进行验证的结果吗？第三行应该是在原始数据集上的测试结果？
> 
> 我这里重新更换了mmdetection版本，并重新检查了所有的参数，获得了新的结果。（还是和论文的结果有些差距，mAP低0.7，mAP50 低5） ![image](https://user-images.githubusercontent.com/89434519/173364289-c38dea67-9469-443f-ad92-7cd3b85eafd3.png)

是和论文report相差一点，另外版本不同带来的影响这么大吗

**Comment by PuAnysh** [comment]
> > > > @caiyaya , hello, 我使用了提供的ckpt与json文件，是可以获得和论文接近的结果的。第二个阶段测试有些问题吧？ ![image](https://user-images.githubusercontent.com/32922494/173358286-2470df16-cf23-48f4-9926-14b0f17a0748.png)
> > > 
> > > 
> > > 感谢您的回复！我是使用了ckpt，以及提供的测试文件(ufpmp_det_eval.py)，我的理解是使用coarse det完成初步预测并生成行的Mosic image，然后使用Mp-det进行预测，并生成新的json文件，最后和val数据集提供的json文件(instances_UAVval.json)进行验证。我这边的测试结果似乎没有达到论文所给定的精度，我不知道是不是没有理解论文的意思或是哪里出现了问题？ By the way, 您这里第二行MP-Det是在生成的UFP数据集上进行验证的结果吗？第三行应该是在原始数据集上的测试结果？
> > 
> > 
> > 我这里重新更换了mmdetection版本，并重新检查了所有的参数，获得了新的结果。（还是和论文的结果有些差距，mAP低0.7，mAP50 低5） ![image](https://user-images.githubusercontent.com/89434519/173364289-c38dea67-9469-443f-ad92-7cd3b85eafd3.png)
> 
> 是和论文report相差一点，另外版本不同带来的影响这么大吗

Hi，你这个是直接从COCO的评测指标算出来的结果。实际上，VisDrone上存在很多ignore区域，这些区域检测出来的框要去除掉。这个可以看VisDrone原始的测评代码（https://github.com/VisDrone/VisDrone2018-DET-toolkit）。
我在这里提供了一个简单工具帮助你转化过去：
工具地址：https://github.com/PuAnysh/UFPMP-Det/blob/main/UFPMP-Det-Tools/eval_script/coco2VisDrone.py
请修改里面的hard code。
然后应该能得到这个结果：
![image](https://user-images.githubusercontent.com/34938360/173368387-ab4b56d1-600d-446f-bfa4-5a141dd6d845.png)
